const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const modules=[['📋','Daily Checklist','Opening • Closing • Hygiene','checklists'],['🍽️','Restaurant Operations','สถานะร้านอาหารและพื้นที่','restaurants'],['⭐','Guest Feedback','Complaint • Review • Recovery','complaints'],['📦','Stock & BOM','Stock • Par • Food Cost','stock'],['🎉','Banquet & Events','Function Sheet • Event','banquet'],['📚','SOP & Training','SOP • Training • Assessment','training'],['🧑‍🍳','Kitchen Operations','Production • Safety • Hygiene','kitchen'],['📊','F&B Reports','KPI • Daily • Monthly','reports'],['🚨','Incident Report','Incident • Action • Follow-up','incident'],['👥','Team Management','Users • Roles • Permission','team']];
const pages={complaints:['Complaints','Guest Complaint / Review / Service Recovery'],history:['History','ประวัติการตรวจ การแก้ไข และกิจกรรมผู้ใช้งาน'],incident:['Incident','รายงานเหตุการณ์และติดตามการแก้ไข'],team:['Team Management','ผู้ใช้งาน ตำแหน่ง และสิทธิ์'],settings:['Settings','ตั้งค่าระบบ F&B'],restaurants:['Restaurant Operations','จัดการร้านอาหาร แยกตามชั้นและพื้นที่'],checklists:['Daily Checklist','หัวข้อตรวจ Opening / Service / Closing / Hygiene'],stock:['Stock & BOM','วัตถุดิบ Par Level และ BOM'],banquet:['Banquet & Events','งานจัดเลี้ยงและ Function Sheet'],training:['SOP & Training','มาตรฐานบริการและ Training'],kitchen:['Kitchen Operations','Production / Hygiene / Food Safety'],reports:['F&B Reports','รายงาน KPI และผลการปฏิบัติงาน'],announcements:['Announcements','ประกาศและการสื่อสารภายใน']};
const defaults={restaurants:[{name:'Restaurant 76F',floor:'76F',status:'กำลังเปิดบริการ',state:'open'},{name:'Restaurant 78F',floor:'78F',status:'กำลังเปิดบริการ',state:'open'},{name:'Stella Palace',floor:'79F',status:'กำลังเตรียมพื้นที่',state:'busy'},{name:'Bangkok Balcony',floor:'81F',status:'กำลังเปิดบริการ',state:'open'},{name:'Crystal Grill',floor:'82F',status:'กำลังเปิดบริการ',state:'open'},{name:'Roof Top Bar',floor:'83F',status:'กำลังเตรียมพื้นที่',state:'busy'}],users:[{name:'Admin',role:'Super Admin',area:'ทุกพื้นที่'},{name:'F&B Manager',role:'Manager',area:'ทุกพื้นที่'},{name:'Supervisor 76F',role:'Supervisor',area:'76F'},{name:'Supervisor 78F',role:'Supervisor',area:'78F'}],checklists:[{name:'Personal Appearance',area:'ทุกพื้นที่',status:'ผ่าน 98%',assignee:'Supervisor'},{name:'Buffet Replenishment',area:'78F',status:'กำลังตรวจ',assignee:'Captain'},{name:'Food Temperature',area:'76F',status:'ผ่าน 100%',assignee:'Kitchen'},{name:'Opening Area Readiness',area:'ทุกพื้นที่',status:'รอตรวจ',assignee:'Supervisor'}],complaints:[{time:'10:20',channel:'Google',area:'78F',topic:'Service',status:'ติดตาม',detail:'ลูกค้ารอการติดตาม'},{time:'11:45',channel:'Facebook',area:'76F',topic:'Food Quality',status:'ปิดเคส',detail:'ตรวจสอบและแจ้งผลแล้ว'},{time:'12:05',channel:'Wongnai',area:'79F',topic:'Waiting Time',status:'ติดตาม',detail:'ตรวจสอบเวลารอ'}],incidents:[{time:'09:40',area:'78F',type:'Safety',severity:'Medium',status:'กำลังติดตาม',detail:'พื้นเปียกบริเวณทางเข้า'},{time:'11:10',area:'Banquet',type:'Service',severity:'Low',status:'ปิดแล้ว',detail:'อุปกรณ์เสิร์ฟไม่ครบ'}],stock:[{item:'Coffee Beans',unit:'kg',par:15,onhand:12,status:'ต่ำกว่า Par'},{item:'Milk',unit:'L',par:40,onhand:28,status:'ต่ำกว่า Par'},{item:'Orange Juice',unit:'L',par:25,onhand:31,status:'ปกติ'}],events:[{time:'15:00',name:'Corporate Dinner',area:'Banquet',status:'Confirm'},{time:'18:30',name:'Group Buffet',area:'78F',status:'Running'},{time:'19:00',name:'Private Dinner',area:'76F',status:'Confirm'}],announcements:[{title:'Service Standard Update',text:'ทบทวนมาตรฐาน Greeting & Seating ก่อนเริ่ม Shift',date:'วันนี้'},{title:'Banquet Briefing',text:'ประชุมเตรียมงาน Event รอบเย็น เวลา 15:00 น.',date:'เมื่อวาน'}],settings:{hotel:'Baiyoke Sky Hotel',system:'F&B Operations Hub',language:'ไทย / English'}};
let data=JSON.parse(localStorage.getItem('baiyokeHubV12')||'null')||defaults;const save=()=>localStorage.setItem('baiyokeHubV12',JSON.stringify(data));
function showDashboard(){ $('#login').classList.add('hidden');$('#subpage').classList.add('hidden');$('#dashboard').classList.remove('hidden');renderDashboard(); }
function renderDashboard(){ $('#restaurantList').innerHTML=data.restaurants.map(r=>`<div class="restaurant"><div><b>${r.name}</b><small>ชั้น ${r.floor}</small></div><span class="status ${r.state||'open'}">${r.status}</span></div>`).join('');$('#moduleGrid').innerHTML=modules.map(m=>`<div class="module" data-page="${m[3]}"><div class="mi">${m[0]}</div><h4>${m[1]}</h4><p>${m[2]}</p></div>`).join('');$('#announcements').innerHTML=data.announcements.slice(0,3).map(a=>`<div class="announcement"><b>${a.title}</b><span>${a.date}</span><p>${a.text}</p></div>`).join('')||'<div class="empty">ยังไม่มีประกาศ</div>';bindPageButtons();}
function bindPageButtons(){$$('[data-page]').forEach(b=>b.onclick=()=>openPage(b.dataset.page));}
function openPage(key){$('#dashboard').classList.add('hidden');$('#login').classList.add('hidden');$('#subpage').classList.remove('hidden');const p=pages[key]||[key,'F&B Operations Module'];$('#subTitle').textContent=p[0];$('#subDesc').textContent=p[1];$('#subContent').innerHTML=content(key);bindPageButtons();}
function toolbar(addLabel,addFn='') {return `<div class="page-toolbar"><div class="search"><span>⌕</span><input id="pageSearch" placeholder="ค้นหา..."></div><button class="primary" ${addFn?`onclick="${addFn}"`:''}>${addLabel}</button></div>`}
function content(key){
 if(key==='restaurants') return toolbar('+ เพิ่มร้านอาหาร','addRestaurant()')+`<div class="sub-cards">${data.restaurants.map((r,i)=>`<div class="sub-card"><div class="card-top"><span class="floor">${r.floor}</span><span class="status ${r.state||'open'}">${r.status}</span></div><h3>${r.name}</h3><p>พื้นที่ปฏิบัติงาน F&B</p><button class="ghost" onclick="editRestaurant(${i})">แก้ไข</button> <button class="ghost danger" onclick="deleteItem('restaurants',${i},'ร้านอาหาร')">ลบ</button></div>`).join('')}</div>`;
 if(key==='checklists') return checklistPage();
 if(key==='complaints') return toolbar('+ บันทึก Complaint','addComplaint()')+`<div class="sub-cards"><div class="sub-card metric"><h3>${data.complaints.length}</h3><p>Feedback ทั้งหมด</p></div><div class="sub-card metric"><h3>${data.complaints.filter(x=>x.status!=='ปิดเคส').length}</h3><p>รอดำเนินการ</p></div><div class="sub-card metric"><h3>${data.complaints.filter(x=>x.status==='ปิดเคส').length}</h3><p>ปิดเคสแล้ว</p></div></div><br><div class="panel"><table class="table"><tr><th>เวลา</th><th>ช่องทาง</th><th>พื้นที่</th><th>หัวข้อ</th><th>สถานะ</th><th></th></tr>${data.complaints.map((c,i)=>`<tr><td>${c.time}</td><td>${c.channel}</td><td>${c.area}</td><td>${c.topic}</td><td class="${c.status==='ปิดเคส'?'':'gold'}">${c.status}</td><td><button class="mini" onclick="viewComplaint(${i})">ดู</button></td></tr>`).join('')}</table></div>`;
 if(key==='incident') return toolbar('+ บันทึก Incident','addIncident()')+`<div class="panel"><table class="table"><tr><th>เวลา</th><th>พื้นที่</th><th>ประเภท</th><th>Severity</th><th>สถานะ</th><th></th></tr>${data.incidents.map((x,i)=>`<tr><td>${x.time}</td><td>${x.area}</td><td>${x.type}</td><td>${x.severity}</td><td class="gold">${x.status}</td><td><button class="mini" onclick="viewIncident(${i})">ดู</button></td></tr>`).join('')}</table></div>`;
 if(key==='team') return toolbar('+ เพิ่มผู้ใช้งาน','addUser()')+`<div class="panel"><table class="table"><tr><th>ชื่อ</th><th>ตำแหน่ง</th><th>พื้นที่</th><th></th></tr>${data.users.map((u,i)=>`<tr><td><b>${u.name}</b></td><td>${u.role}</td><td>${u.area}</td><td><button class="mini" onclick="editUser(${i})">แก้ไข</button> <button class="mini" onclick="deleteItem('users',${i},'ผู้ใช้งาน')">ลบ</button></td></tr>`).join('')}</table></div>`;
 if(key==='stock') return toolbar('+ เพิ่มรายการ Stock','addStock()')+`<div class="panel"><table class="table"><tr><th>วัตถุดิบ</th><th>หน่วย</th><th>Par</th><th>คงเหลือ</th><th>สถานะ</th></tr>${data.stock.map(x=>`<tr><td><b>${x.item}</b></td><td>${x.unit}</td><td>${x.par}</td><td>${x.onhand}</td><td class="${x.onhand<x.par?'gold':''}">${x.status}</td></tr>`).join('')}</table></div>`;
 if(key==='banquet') return toolbar('+ เพิ่ม Event','addEvent()')+`<div class="sub-cards">${data.events.map((x,i)=>{const e=eventObj(x);return `<div class="sub-card event-card" onclick="viewEvent(${i})" style="cursor:pointer"><div class="card-top"><span class="floor">${e.time}</span><span class="status">${e.status}</span></div><h3>${e.name}</h3><p>${e.area}${e.pax?` • ${e.pax} PAX`:''}</p><small>${e.menuType||'Banquet'}${e.room?` • ${e.room}`:''}</small><br><button class="ghost" onclick="event.stopPropagation();viewEvent(${i})">ดูรายละเอียด</button></div>`}).join('')}</div>`;
 if(key==='training') return `<div class="sub-cards"><div class="sub-card"><div class="mi">👋</div><h3>Greeting & Seating</h3><p>มาตรฐานการต้อนรับและจัดที่นั่ง</p><button class="ghost">เปิด SOP</button></div><div class="sub-card"><div class="mi">🍴</div><h3>Menu Recommendation</h3><p>ความรู้เมนูและการแนะนำรายการอาหาร</p><button class="ghost">เปิด SOP</button></div><div class="sub-card"><div class="mi">🛡️</div><h3>Food Allergy</h3><p>ขั้นตอนรับคำขอพิเศษและ Food Allergy</p><button class="ghost">เปิด SOP</button></div></div>`;
 if(key==='reports') return `<div class="sub-cards"><div class="sub-card metric"><h3>86%</h3><p>Checklist Completion</p></div><div class="sub-card metric"><h3>${data.complaints.length}</h3><p>Guest Feedback</p></div><div class="sub-card metric"><h3>${data.incidents.length}</h3><p>Incident</p></div></div><br><div class="panel"><h3>Daily F&B Summary</h3><p>ภาพรวมข้อมูล Demo สำหรับใช้เป็นโครงสร้างรายงานจริง</p><div class="progress"><span style="width:86%"></span></div><div class="legend">Checklist Completion 86%</div></div>`;
 if(key==='announcements') return toolbar('+ เพิ่มประกาศ','addAnnouncement()')+`<div class="panel">${data.announcements.map((a,i)=>`<div class="announcement"><b>${a.title}</b><span>${a.date}</span><p>${a.text}</p><button class="mini" onclick="deleteItem('announcements',${i},'ประกาศ')">ลบ</button></div>`).join('')||'<div class="empty">ยังไม่มีประกาศ</div>'}</div>`;
 if(key==='settings') return `<div class="panel settings"><h3>System Settings</h3><label>ชื่อโรงแรม<input id="setHotel" value="${data.settings.hotel}"></label><label>ชื่อระบบ<input id="setSystem" value="${data.settings.system}"></label><label>ภาษา<select id="setLang"><option ${data.settings.language==='ไทย / English'?'selected':''}>ไทย / English</option><option>ไทย</option><option>English</option></select></label><button class="primary" onclick="saveSettings()">บันทึกการตั้งค่า</button></div>`;
 if(key==='history') return `<div class="panel"><div class="timeline"><div><b>วันนี้ 12:05</b><span>Guest Feedback • Wongnai • 79F</span></div><div><b>วันนี้ 11:45</b><span>Complaint ปิดเคส • Facebook • 76F</span></div><div><b>วันนี้ 11:10</b><span>Incident บันทึก • Banquet</span></div><div><b>วันนี้ 10:20</b><span>Checklist ตรวจ • 78F</span></div></div></div>`;
 if(key==='kitchen') return `<div class="sub-cards"><div class="sub-card"><h3>🌡️ Food Temperature</h3><p>ตรวจและบันทึกอุณหภูมิอาหารตามรอบ</p><button class="ghost" data-page="checklists">เปิด Checklist</button></div><div class="sub-card"><h3>🧼 Hygiene</h3><p>สุขอนามัยพื้นที่ผลิตและอุปกรณ์</p><button class="ghost" data-page="checklists">ตรวจพื้นที่</button></div><div class="sub-card"><h3>🧑‍🍳 Production</h3><p>Production plan และการเตรียมวัตถุดิบ</p><button class="ghost" data-page="stock">ดู Stock</button></div></div>`;
 return `<div class="sub-cards"><div class="sub-card"><div class="mi">${modules.find(m=>m[3]===key)?.[0]||'⚙️'}</div><h3>${pLabel(key)}</h3><p>Demo module พร้อมต่อยอดเป็นระบบจริงและเชื่อมฐานข้อมูลกลาง</p><button class="ghost">เริ่มใช้งาน</button></div><div class="sub-card"><h3>Quick Action</h3><p>สร้างรายการใหม่ แก้ไขข้อมูล หรือดูประวัติการทำงาน</p><button class="ghost">+ สร้างรายการ</button></div></div>`;
}

function checklistPage(){
 const runs=data.checklistRuns||[];
 const done=runs.filter(x=>x.result==='ผ่าน').length, fail=runs.filter(x=>x.result==='ไม่ผ่าน').length, total=runs.length;
 return toolbar('+ เริ่มตรวจ Checklist','startChecklist()')+
 `<div class="sub-cards"><div class="sub-card metric"><h3>${data.checklists.length}</h3><p>หัวข้อตรวจ</p></div><div class="sub-card metric"><h3>${done}</h3><p>ผ่าน</p></div><div class="sub-card metric"><h3>${fail}</h3><p>ไม่ผ่าน</p></div></div><br>
 <div class="panel"><div class="panel-title"><div><h3>รายการ Checklist</h3><p>เลือกพื้นที่และ Shift เพื่อเริ่มการตรวจจริง</p></div><span class="badge">${total} รายการที่บันทึก</span></div>
 <div class="checklist-list">${data.checklists.map((c,i)=>`<div class="check-row"><div><b>${c.name}</b><small>${c.area} • ผู้รับผิดชอบ ${c.assignee}</small></div><span class="status ${c.status==='รอตรวจ'?'busy':'open'}">${c.status}</span><button class="mini" onclick="quickCheck(${i})">ตรวจ</button><button class="mini" onclick="editChecklist(${i})">แก้ไข</button></div>`).join('')}</div></div>
 <br><div class="panel"><div class="panel-title"><div><h3>ประวัติการตรวจล่าสุด</h3><p>เก็บผล ✓ / ✕, Remark และรูปประกอบ</p></div></div>${runs.slice().reverse().slice(0,8).map((r,i)=>`<div class="history-row"><div><b>${r.item}</b><small>${r.area} • ${r.shift} • ${r.inspector} • ${r.time}</small></div><span class="result ${r.result==='ผ่าน'?'pass':'fail'}">${r.result}</span><button class="mini" onclick="viewCheckRun(${runs.length-1-i})">ดู</button></div>`).join('')||'<div class="empty">ยังไม่มีผลการตรวจ</div>'}</div>`;
}
function checklistForm(){return `<div class="form"><div class="form-grid"><label>ร้าน / พื้นที่<select id="runArea">${data.restaurants.map(r=>`<option>${r.floor} • ${r.name}</option>`).join('')}<option>ทุกพื้นที่</option></select></label><label>Shift<select id="runShift"><option>Opening</option><option>Service</option><option>Closing</option></select></label><label>ผู้ตรวจ<input id="runInspector" value="Supervisor"></label><label>วันที่ / เวลา<input id="runTime" type="datetime-local"></label></div><div id="runItems" class="run-items">${data.checklists.map((c,i)=>`<div class="run-item"><div><b>${c.name}</b><small>${c.area}</small></div><div class="check-buttons"><button type="button" class="result-btn pass-btn" data-i="${i}" data-result="ผ่าน">✓ ผ่าน</button><button type="button" class="result-btn fail-btn" data-i="${i}" data-result="ไม่ผ่าน">✕ ไม่ผ่าน</button></div><input class="run-remark" data-i="${i}" placeholder="Remark / สิ่งที่ต้องแก้ไข"></div>`).join('')}</div><label>หมายเหตุรวม<textarea id="runNote" rows=3 placeholder="รายละเอียดเพิ่มเติม"></textarea></label><label>รูปประกอบ (Demo)<input id="runPhoto" type="file" accept="image/*"></label><button class="primary" onclick="submitChecklistRun()">✓ Submit Checklist</button></div>`}
window.startChecklist=()=>{modal('เริ่มตรวจ Daily Checklist',checklistForm());const d=new Date();$('#runTime').value=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);bindRunButtons()};
window.quickCheck=i=>{modal('ตรวจ: '+data.checklists[i].name,`<div class="form"><p><b>${data.checklists[i].name}</b></p><label>พื้นที่<input id="qArea" value="${data.checklists[i].area}"></label><label>ผู้ตรวจ<input id="qInspector" value="Supervisor"></label><div class="check-buttons large"><button class="result-btn pass-btn" onclick="saveQuick(${i},'ผ่าน')">✓ ผ่าน</button><button class="result-btn fail-btn" onclick="saveQuick(${i},'ไม่ผ่าน')">✕ ไม่ผ่าน</button></div><label>Remark<textarea id="qRemark" rows=3></textarea></label></div>`)};
window.saveQuick=(i,result)=>{data.checklistRuns=data.checklistRuns||[];data.checklistRuns.push({item:data.checklists[i].name,area:$('#qArea').value,shift:'Quick Check',inspector:$('#qInspector').value,result,remark:$('#qRemark').value,time:new Date().toLocaleString('th-TH')});data.checklists[i].status=result==='ผ่าน'?'ผ่าน':'ไม่ผ่าน';save();closeAllModals();openPage('checklists')};
function bindRunButtons(){$$('.result-btn').forEach(b=>b.onclick=()=>{const i=b.dataset.i;$$(`.result-btn[data-i="${i}"]`).forEach(x=>x.classList.remove('selected'));b.classList.add('selected');b.closest('.run-item').dataset.result=b.dataset.result})}
window.submitChecklistRun=()=>{const items=$$('#runItems .run-item');data.checklistRuns=data.checklistRuns||[];let count=0;items.forEach((el,i)=>{if(!el.dataset.result)return;count++;data.checklistRuns.push({item:data.checklists[i].name,area:$('#runArea').value,shift:$('#runShift').value,inspector:$('#runInspector').value,result:el.dataset.result,remark:el.querySelector('.run-remark').value,time:new Date($('#runTime').value||Date.now()).toLocaleString('th-TH')});data.checklists[i].status=el.dataset.result==='ผ่าน'?'ผ่าน':'ไม่ผ่าน'});if(!count){alert('กรุณาเลือกผลตรวจอย่างน้อย 1 หัวข้อ');return}save();closeAllModals();openPage('checklists')};
window.viewCheckRun=i=>{const r=(data.checklistRuns||[])[i];if(!r)return;modal('Checklist Result',`<div class="detail"><p><b>หัวข้อ:</b> ${r.item}</p><p><b>พื้นที่:</b> ${r.area}</p><p><b>Shift:</b> ${r.shift}</p><p><b>ผู้ตรวจ:</b> ${r.inspector}</p><p><b>ผล:</b> <span class="result ${r.result==='ผ่าน'?'pass':'fail'}">${r.result}</span></p><p><b>Remark:</b> ${r.remark||'-'}</p><p><b>เวลา:</b> ${r.time}</p></div>`)};
function pLabel(k){return pages[k]?.[0]||k}
function modal(title,body){const m=document.createElement('div');m.className='modal';m.innerHTML=`<div class="modal-box"><div class="modal-head"><h3>${title}</h3><button onclick="this.closest('.modal').remove()">✕</button></div>${body}</div>`;document.body.appendChild(m)}
function formModal(title,fields,onSave){modal(title,`<div class="form">${fields.map(f=>`<label>${f.label}<input id="f_${f.id}" value="${f.value||''}" placeholder="${f.placeholder||''}"></label>`).join('')}<button class="primary" id="saveForm">บันทึก</button></div>`);$('#saveForm').onclick=()=>{const vals=Object.fromEntries(fields.map(f=>[f.id,$('#f_'+f.id).value.trim()]));onSave(vals);document.querySelector('.modal')?.remove();save();renderCurrent();}}
function renderCurrent(){const title=$('#subTitle').textContent;const key=Object.keys(pages).find(k=>pages[k][0]===title)||'dashboard';if(key==='dashboard')showDashboard();else openPage(key)}
window.addRestaurant=()=>formModal('เพิ่มร้านอาหาร',[{id:'name',label:'ชื่อร้านอาหาร'},{id:'floor',label:'ชั้น'}],v=>data.restaurants.push({name:v.name,floor:v.floor,status:'กำลังเปิดบริการ',state:'open'}));
window.editRestaurant=i=>formModal('แก้ไขร้านอาหาร',[{id:'name',label:'ชื่อร้านอาหาร',value:data.restaurants[i].name},{id:'floor',label:'ชั้น',value:data.restaurants[i].floor},{id:'status',label:'สถานะ',value:data.restaurants[i].status}],v=>Object.assign(data.restaurants[i],{name:v.name,floor:v.floor,status:v.status}));
window.addChecklist=()=>formModal('เพิ่มหัวข้อตรวจ',[{id:'name',label:'หัวข้อตรวจ'},{id:'area',label:'พื้นที่',value:'ทุกพื้นที่'},{id:'assignee',label:'ผู้ตรวจ',value:'Supervisor'}],v=>data.checklists.push({name:v.name,area:v.area,status:'รอตรวจ',assignee:v.assignee}));
window.editChecklist=i=>formModal('แก้ไข Checklist',[{id:'name',label:'หัวข้อตรวจ',value:data.checklists[i].name},{id:'area',label:'พื้นที่',value:data.checklists[i].area},{id:'status',label:'สถานะ',value:data.checklists[i].status},{id:'assignee',label:'ผู้ตรวจ',value:data.checklists[i].assignee}],v=>Object.assign(data.checklists[i],v));
window.addComplaint=()=>formModal('บันทึก Complaint',[{id:'channel',label:'ช่องทาง',value:'Google'},{id:'area',label:'พื้นที่',value:'76F'},{id:'topic',label:'หัวข้อ'},{id:'detail',label:'รายละเอียด'}],v=>data.complaints.push({time:new Date().toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'}),channel:v.channel,area:v.area,topic:v.topic,status:'ติดตาม',detail:v.detail}));
window.viewComplaint=i=>modal('Complaint Detail',`<div class="detail"><p><b>ช่องทาง:</b> ${data.complaints[i].channel}</p><p><b>พื้นที่:</b> ${data.complaints[i].area}</p><p><b>หัวข้อ:</b> ${data.complaints[i].topic}</p><p><b>รายละเอียด:</b> ${data.complaints[i].detail}</p><button class="primary" onclick="closeAllModals();data.complaints[${i}].status='ปิดเคส';save();openPage('complaints')">ปิดเคส</button></div>`);
window.addIncident=()=>formModal('บันทึก Incident',[{id:'area',label:'พื้นที่',value:'76F'},{id:'type',label:'ประเภท',value:'Safety'},{id:'severity',label:'Severity',value:'Low'},{id:'detail',label:'รายละเอียด'}],v=>data.incidents.push({time:new Date().toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'}),area:v.area,type:v.type,severity:v.severity,status:'กำลังติดตาม',detail:v.detail}));
window.viewIncident=i=>modal('Incident Detail',`<div class="detail"><p><b>เวลา:</b> ${data.incidents[i].time}</p><p><b>พื้นที่:</b> ${data.incidents[i].area}</p><p><b>ประเภท:</b> ${data.incidents[i].type}</p><p><b>รายละเอียด:</b> ${data.incidents[i].detail}</p></div>`);
window.addUser=()=>formModal('เพิ่มผู้ใช้งาน',[{id:'name',label:'ชื่อ-นามสกุล'},{id:'role',label:'ตำแหน่ง',value:'Staff'},{id:'area',label:'พื้นที่',value:'ทุกพื้นที่'}],v=>data.users.push(v));
window.editUser=i=>formModal('แก้ไขผู้ใช้งาน',[{id:'name',label:'ชื่อ-นามสกุล',value:data.users[i].name},{id:'role',label:'ตำแหน่ง',value:data.users[i].role},{id:'area',label:'พื้นที่',value:data.users[i].area}],v=>Object.assign(data.users[i],v));
window.addStock=()=>formModal('เพิ่ม Stock',[{id:'item',label:'วัตถุดิบ'},{id:'unit',label:'หน่วย',value:'unit'},{id:'par',label:'Par',value:'10'},{id:'onhand',label:'คงเหลือ',value:'0'}],v=>data.stock.push({item:v.item,unit:v.unit,par:Number(v.par),onhand:Number(v.onhand),status:Number(v.onhand)<Number(v.par)?'ต่ำกว่า Par':'ปกติ'}));
window.addEvent=()=>formModal('เพิ่ม Event',[{id:'time',label:'เวลา',value:'18:00'},{id:'name',label:'ชื่องาน'},{id:'area',label:'พื้นที่ / Restaurant',value:'Banquet'},{id:'room',label:'ห้องจัดงาน / Function Room',value:''},{id:'pax',label:'จำนวนแขก (PAX)',value:'100'},{id:'menuType',label:'รูปแบบอาหาร',value:'Buffet'},{id:'menu',label:'Menu',value:''},{id:'beverage',label:'Beverage',value:''}],v=>data.events.push({...v,status:'Confirm'}));
function eventObj(x){return Array.isArray(x)?{time:x[0],name:x[1],area:x[2],status:x[3]}:x;}
window.viewEvent=i=>{const e=eventObj(data.events[i]);modal('Event Detail • Function Sheet',`<div class="detail event-detail"><div class="detail-grid"><p><b>ชื่องาน:</b> ${e.name||'-'}</p><p><b>สถานะ:</b> ${e.status||'-'}</p><p><b>เวลา:</b> ${e.time||'-'}</p><p><b>พื้นที่:</b> ${e.area||'-'}</p><p><b>Function Room:</b> ${e.room||'-'}</p><p><b>PAX:</b> ${e.pax||'-'}</p><p><b>รูปแบบอาหาร:</b> ${e.menuType||'-'}</p><p><b>Menu:</b> ${e.menu||'-'}</p><p><b>Beverage:</b> ${e.beverage||'-'}</p><p><b>Kitchen / Chef:</b> ${e.chef||'ยังไม่กำหนด'}</p><p><b>Service Captain:</b> ${e.captain||'ยังไม่กำหนด'}</p><p><b>Staff:</b> ${e.staff||'ยังไม่กำหนด'}</p></div><hr><h4>Event Checklist</h4><div class="check-list"><label>☐ Function Room Setup</label><label>☐ Table / Equipment Ready</label><label>☐ Kitchen Briefing</label><label>☐ Service Team Briefing</label><label>☐ Menu & Beverage Ready</label><label>☐ Final Guest Count</label></div><div class="event-actions"><button class="primary" onclick="closeAllModals();eventPlan(${i})">วางแผนงาน</button></div></div>`)};
window.eventPlan=i=>{const e=eventObj(data.events[i]);modal('Event Planning • '+e.name,`<div class="form"><label>Kitchen / Chef<input id="epChef" value="${e.chef||''}" placeholder="Chef in charge"></label><label>Service Captain<input id="epCaptain" value="${e.captain||''}" placeholder="Captain / Supervisor"></label><label>Staff จำนวน / รายชื่อ<input id="epStaff" value="${e.staff||''}" placeholder="เช่น 8 คน / รายชื่อ"></label><label>Timeline<textarea id="epTimeline" rows=4 placeholder="15:00 Setup\n16:00 Briefing\n17:30 Final Check\n18:00 Guest Arrival">${e.timeline||''}</textarea></label><label>หมายเหตุ<textarea id="epNote" rows=3 placeholder="Issue / Special Request">${e.note||''}</textarea></label><button class="primary" onclick="saveEventPlan(${i})">บันทึกแผนงาน</button></div>`)};
window.saveEventPlan=i=>{let e=eventObj(data.events[i]);Object.assign(e,{chef:$('#epChef').value,captain:$('#epCaptain').value,staff:$('#epStaff').value,timeline:$('#epTimeline').value,note:$('#epNote').value,status:'Planned'});data.events[i]=e;save();closeAllModals();openPage('banquet')};
window.addAnnouncement=()=>formModal('เพิ่มประกาศ',[{id:'title',label:'หัวข้อ'},{id:'text',label:'รายละเอียด'}],v=>data.announcements.unshift({...v,date:'วันนี้'}));
window.saveSettings=()=>{data.settings.hotel=$('#setHotel').value;data.settings.system=$('#setSystem').value;data.settings.language=$('#setLang').value;save();alert('บันทึกการตั้งค่าแล้ว')};
window.deleteItem=(type,i,label)=>{if(confirm(`ต้องการลบ${label}นี้หรือไม่?`)){data[type].splice(i,1);save();renderCurrent()}};window.closeAllModals=()=>$$('.modal').forEach(m=>m.remove());
const pin=$$('#pinBoxes input');pin.forEach((e,i)=>{e.oninput=()=>{e.value=e.value.replace(/\D/g,'').slice(0,1);if(e.value&&pin[i+1])pin[i+1].focus()};e.onkeydown=x=>{if(x.key==='Backspace'&&!e.value&&pin[i-1])pin[i-1].focus();if(x.key==='Enter')$('#loginBtn').click()}});$('#loginBtn').onclick=()=>{if(pin.map(x=>x.value).join('')==='1234'){showDashboard()}else alert('รหัสผ่านไม่ถูกต้อง (Demo: 1234)')};$('#resetDemo').onclick=()=>{pin.forEach(x=>x.value='');pin[0].focus()};$('#loginNav').onclick=()=>{$('#dashboard').classList.add('hidden');$('#subpage').classList.add('hidden');$('#login').classList.remove('hidden')};$('#logoutBtn').onclick=()=>location.reload();$('#backDash').onclick=showDashboard;$('#floorFilter').onchange=e=>{const f=e.target.value;const rows=f==='ทุกพื้นที่'?data.restaurants:data.restaurants.filter(r=>r.floor===f);$('#restaurantList').innerHTML=rows.map(r=>`<div class="restaurant"><div><b>${r.name}</b><small>ชั้น ${r.floor}</small></div><span class="status ${r.state||'open'}">${r.status}</span></div>`).join('')};bindPageButtons();
